services:
  backend_service:
    build: .
    env_file: .env
    restart: always
    ports:
      - '8001:8000'
    depends_on:
      - postgres_service
      - minio_service
      - flower_service
      - redis_service

  postgres_service:
    image: postgres:alpine
    volumes:
      - pg_data_service:/var/lib/postgresql/data
    env_file: .env

  minio_service:
    image: minio/minio
    volumes:
      - minio_storage:/data
    env_file: .env
    command: server --console-address ":9001" /data


#
#  redis:
#    image: redis:6.2-alpine
#    volumes:
#      - redis_data:/data
#    environment:
#      - REDIS_PASSWORD
#      - REDIS_PORT
#    env_file:
#      - .env
#
#  flower:
#    build:
#      context: .
##      dockerfile: ./Dockerfile
##    command: /start-flower
#    volumes:
#      - .:/app
#    ports:
#      - 5557:5555
#    depends_on:
#      - redis
#      - postgres_service
#
#volumes:
#  minio_storage:
#  pg_data_service:
#  redis_data:
#
#  redis:
#    image: redis:6.2-alpine
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis_data:/data
#    environment:
#      - REDIS_PASSWORD=my-password
#      - REDIS_PORT=6379




